modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Creative-Apiary/issues/new/choose"
[[mods]]
modId="creativeapiary"
version="${file.jarVersion}"
displayName="Creative Apiary"
displayURL="https://www.curseforge.com/minecraft/mc-mods/creative-apiary"
logoFile="examplemod.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds a Creative Apiary."

[[dependencies.creativeapiary]]
    modId="resourcefulbees"
    mandatory=true
    versionRange="[1.16.5-0.9.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativeapiary]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativeapiary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"